-- MySQL Script generated by MySQL Workbench
-- Wed May  9 00:00:08 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sef
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sef
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sef` ;
USE `sef` ;

-- -----------------------------------------------------
-- Table `sef`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sef`.`admin` ;

CREATE TABLE IF NOT EXISTS `sef`.`admin` (
  `userId` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sef`.`coordinator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sef`.`coordinator` ;

CREATE TABLE IF NOT EXISTS `sef`.`coordinator` (
  `userId` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sef`.`lecturer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sef`.`lecturer` ;

CREATE TABLE IF NOT EXISTS `sef`.`lecturer` (
  `userId` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sef`.`student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sef`.`student` ;

CREATE TABLE IF NOT EXISTS `sef`.`student` (
  `userId` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `maxLoad` INT NULL DEFAULT 1,
  `maxElectives` INT NULL DEFAULT 1,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sef`.`course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sef`.`course` ;

CREATE TABLE IF NOT EXISTS `sef`.`course` (
  `code` VARCHAR(45) NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `mainTopic` VARCHAR(500) NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sef`.`prerequisites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sef`.`prerequisites` ;

CREATE TABLE IF NOT EXISTS `sef`.`prerequisites` (
  `code` VARCHAR(45) NOT NULL,
  `preCode` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`code`, `preCode`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sef`.`schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sef`.`schedule` ;

CREATE TABLE IF NOT EXISTS `sef`.`schedule` (
  `schId` INT NOT NULL AUTO_INCREMENT,
  `year` INT NOT NULL DEFAULT 2018,
  `semester` INT NOT NULL DEFAULT 1,
  `week` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`schId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sef`.`courseOffering`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sef`.`courseOffering` ;

CREATE TABLE IF NOT EXISTS `sef`.`courseOffering` (
  `OfferingId` INT NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `lecId` VARCHAR(45) NOT NULL,
  `schId` INT NOT NULL,
  `capacity` INT NULL,
  PRIMARY KEY (`OfferingId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sef`.`enrolment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sef`.`enrolment` ;

CREATE TABLE IF NOT EXISTS `sef`.`enrolment` (
  `enrolId` INT NOT NULL,
  `stuId` VARCHAR(45) NOT NULL,
  `offeringId` INT NOT NULL,
  `result` VARCHAR(45) NULL DEFAULT 'RNF',
  PRIMARY KEY (`enrolId`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
